### ISSUE TITLE
API to econforecasting

### ISSUE THREAD

**Issue by tp-duarte** [cmefi/econforecasting-r#1]
Hi @bongohead,

Really cool the econforecasting platform!

Was wondering if there is a way to retrieve data via an api instead of downloading the historical/forecasted values in the https://econforecasting.com/ site. 

Thank you and congrats for the work!

**Comment by bongohead** [comment]
There is! It's paid for commercial use but free for any sort of non-corporate research/academic use. It's experimental currently so there are no formal docs yet, but feel free to email me (charles@econforecasting.com) if you're interested.
